// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf Java Version: 4.29.0

package proto;

public final class Messages {
  private Messages() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      Messages.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HistoricalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Historical)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 batchid = 1;</code>
     * @return The batchid.
     */
    long getBatchid();

    /**
     * <code>string sensor = 2;</code>
     * @return The sensor.
     */
    java.lang.String getSensor();
    /**
     * <code>string sensor = 2;</code>
     * @return The bytes for sensor.
     */
    com.google.protobuf.ByteString
        getSensorBytes();

    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    java.util.List<proto.Messages.HistoricalValue> 
        getValuesList();
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    proto.Messages.HistoricalValue getValues(int index);
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    java.util.List<? extends proto.Messages.HistoricalValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    proto.Messages.HistoricalValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Historical}
   */
  public static final class Historical extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Historical)
      HistoricalOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Historical.class.getName());
    }
    // Use Historical.newBuilder() to construct.
    private Historical(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Historical() {
      sensor_ = "";
      values_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Messages.internal_static_your_package_Historical_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Messages.internal_static_your_package_Historical_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Messages.Historical.class, proto.Messages.Historical.Builder.class);
    }

    public static final int BATCHID_FIELD_NUMBER = 1;
    private long batchid_ = 0L;
    /**
     * <code>int64 batchid = 1;</code>
     * @return The batchid.
     */
    @java.lang.Override
    public long getBatchid() {
      return batchid_;
    }

    public static final int SENSOR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sensor_ = "";
    /**
     * <code>string sensor = 2;</code>
     * @return The sensor.
     */
    @java.lang.Override
    public java.lang.String getSensor() {
      java.lang.Object ref = sensor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensor_ = s;
        return s;
      }
    }
    /**
     * <code>string sensor = 2;</code>
     * @return The bytes for sensor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSensorBytes() {
      java.lang.Object ref = sensor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<proto.Messages.HistoricalValue> values_;
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    @java.lang.Override
    public java.util.List<proto.Messages.HistoricalValue> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends proto.Messages.HistoricalValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    @java.lang.Override
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    @java.lang.Override
    public proto.Messages.HistoricalValue getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .proto.HistoricalValue values = 3;</code>
     */
    @java.lang.Override
    public proto.Messages.HistoricalValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (batchid_ != 0L) {
        output.writeInt64(1, batchid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sensor_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, sensor_);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(3, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (batchid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, batchid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sensor_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sensor_);
      }
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Messages.Historical)) {
        return super.equals(obj);
      }
      proto.Messages.Historical other = (proto.Messages.Historical) obj;

      if (getBatchid()
          != other.getBatchid()) return false;
      if (!getSensor()
          .equals(other.getSensor())) return false;
      if (!getValuesList()
          .equals(other.getValuesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BATCHID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBatchid());
      hash = (37 * hash) + SENSOR_FIELD_NUMBER;
      hash = (53 * hash) + getSensor().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Messages.Historical parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.Historical parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.Historical parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.Historical parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.Historical parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.Historical parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.Historical parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.Messages.Historical parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.Messages.Historical parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.Messages.Historical parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Messages.Historical parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.Messages.Historical parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Messages.Historical prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Historical}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Historical)
        proto.Messages.HistoricalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Messages.internal_static_your_package_Historical_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Messages.internal_static_your_package_Historical_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Messages.Historical.class, proto.Messages.Historical.Builder.class);
      }

      // Construct using proto.Messages.Historical.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        batchid_ = 0L;
        sensor_ = "";
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
        } else {
          values_ = null;
          valuesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Messages.internal_static_your_package_Historical_descriptor;
      }

      @java.lang.Override
      public proto.Messages.Historical getDefaultInstanceForType() {
        return proto.Messages.Historical.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Messages.Historical build() {
        proto.Messages.Historical result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Messages.Historical buildPartial() {
        proto.Messages.Historical result = new proto.Messages.Historical(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(proto.Messages.Historical result) {
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
      }

      private void buildPartial0(proto.Messages.Historical result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.batchid_ = batchid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sensor_ = sensor_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Messages.Historical) {
          return mergeFrom((proto.Messages.Historical)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Messages.Historical other) {
        if (other == proto.Messages.Historical.getDefaultInstance()) return this;
        if (other.getBatchid() != 0L) {
          setBatchid(other.getBatchid());
        }
        if (!other.getSensor().isEmpty()) {
          sensor_ = other.sensor_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000004);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                batchid_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                sensor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                proto.Messages.HistoricalValue m =
                    input.readMessage(
                        proto.Messages.HistoricalValue.parser(),
                        extensionRegistry);
                if (valuesBuilder_ == null) {
                  ensureValuesIsMutable();
                  values_.add(m);
                } else {
                  valuesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long batchid_ ;
      /**
       * <code>int64 batchid = 1;</code>
       * @return The batchid.
       */
      @java.lang.Override
      public long getBatchid() {
        return batchid_;
      }
      /**
       * <code>int64 batchid = 1;</code>
       * @param value The batchid to set.
       * @return This builder for chaining.
       */
      public Builder setBatchid(long value) {

        batchid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 batchid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        batchid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sensor_ = "";
      /**
       * <code>string sensor = 2;</code>
       * @return The sensor.
       */
      public java.lang.String getSensor() {
        java.lang.Object ref = sensor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sensor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sensor = 2;</code>
       * @return The bytes for sensor.
       */
      public com.google.protobuf.ByteString
          getSensorBytes() {
        java.lang.Object ref = sensor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sensor = 2;</code>
       * @param value The sensor to set.
       * @return This builder for chaining.
       */
      public Builder setSensor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sensor_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string sensor = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensor() {
        sensor_ = getDefaultInstance().getSensor();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string sensor = 2;</code>
       * @param value The bytes for sensor to set.
       * @return This builder for chaining.
       */
      public Builder setSensorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sensor_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<proto.Messages.HistoricalValue> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          values_ = new java.util.ArrayList<proto.Messages.HistoricalValue>(values_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Messages.HistoricalValue, proto.Messages.HistoricalValue.Builder, proto.Messages.HistoricalValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public java.util.List<proto.Messages.HistoricalValue> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public proto.Messages.HistoricalValue getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder setValues(
          int index, proto.Messages.HistoricalValue value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder setValues(
          int index, proto.Messages.HistoricalValue.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder addValues(proto.Messages.HistoricalValue value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder addValues(
          int index, proto.Messages.HistoricalValue value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder addValues(
          proto.Messages.HistoricalValue.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder addValues(
          int index, proto.Messages.HistoricalValue.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends proto.Messages.HistoricalValue> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public proto.Messages.HistoricalValue.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public proto.Messages.HistoricalValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public java.util.List<? extends proto.Messages.HistoricalValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public proto.Messages.HistoricalValue.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            proto.Messages.HistoricalValue.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public proto.Messages.HistoricalValue.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, proto.Messages.HistoricalValue.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.HistoricalValue values = 3;</code>
       */
      public java.util.List<proto.Messages.HistoricalValue.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Messages.HistoricalValue, proto.Messages.HistoricalValue.Builder, proto.Messages.HistoricalValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.Messages.HistoricalValue, proto.Messages.HistoricalValue.Builder, proto.Messages.HistoricalValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.Historical)
    }

    // @@protoc_insertion_point(class_scope:proto.Historical)
    private static final proto.Messages.Historical DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Messages.Historical();
    }

    public static proto.Messages.Historical getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Historical>
        PARSER = new com.google.protobuf.AbstractParser<Historical>() {
      @java.lang.Override
      public Historical parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Historical> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Historical> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Messages.Historical getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
    public long getTimestamp() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getTimestamp'");
    }

  }

  public interface HistoricalValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.HistoricalValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 t = 1;</code>
     * @return The t.
     */
    long getT();

    /**
     * <code>double v = 2;</code>
     * @return The v.
     */
    double getV();
  }
  /**
   * Protobuf type {@code proto.HistoricalValue}
   */
  public static final class HistoricalValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.HistoricalValue)
      HistoricalValueOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        HistoricalValue.class.getName());
    }
    // Use HistoricalValue.newBuilder() to construct.
    private HistoricalValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HistoricalValue() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Messages.internal_static_your_package_HistoricalValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Messages.internal_static_your_package_HistoricalValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Messages.HistoricalValue.class, proto.Messages.HistoricalValue.Builder.class);
    }

    public static final int T_FIELD_NUMBER = 1;
    private long t_ = 0L;
    /**
     * <code>int64 t = 1;</code>
     * @return The t.
     */
    @java.lang.Override
    public long getT() {
      return t_;
    }

    public static final int V_FIELD_NUMBER = 2;
    private double v_ = 0D;
    /**
     * <code>double v = 2;</code>
     * @return The v.
     */
    @java.lang.Override
    public double getV() {
      return v_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (t_ != 0L) {
        output.writeInt64(1, t_);
      }
      if (java.lang.Double.doubleToRawLongBits(v_) != 0) {
        output.writeDouble(2, v_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (t_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, t_);
      }
      if (java.lang.Double.doubleToRawLongBits(v_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, v_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Messages.HistoricalValue)) {
        return super.equals(obj);
      }
      proto.Messages.HistoricalValue other = (proto.Messages.HistoricalValue) obj;

      if (getT()
          != other.getT()) return false;
      if (java.lang.Double.doubleToLongBits(getV())
          != java.lang.Double.doubleToLongBits(
              other.getV())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getT());
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getV()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Messages.HistoricalValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.HistoricalValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.HistoricalValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.Messages.HistoricalValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.Messages.HistoricalValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.Messages.HistoricalValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Messages.HistoricalValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.HistoricalValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.HistoricalValue)
        proto.Messages.HistoricalValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Messages.internal_static_your_package_HistoricalValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Messages.internal_static_your_package_HistoricalValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Messages.HistoricalValue.class, proto.Messages.HistoricalValue.Builder.class);
      }

      // Construct using proto.Messages.HistoricalValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        t_ = 0L;
        v_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Messages.internal_static_your_package_HistoricalValue_descriptor;
      }

      @java.lang.Override
      public proto.Messages.HistoricalValue getDefaultInstanceForType() {
        return proto.Messages.HistoricalValue.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Messages.HistoricalValue build() {
        proto.Messages.HistoricalValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Messages.HistoricalValue buildPartial() {
        proto.Messages.HistoricalValue result = new proto.Messages.HistoricalValue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.Messages.HistoricalValue result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.t_ = t_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.v_ = v_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Messages.HistoricalValue) {
          return mergeFrom((proto.Messages.HistoricalValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Messages.HistoricalValue other) {
        if (other == proto.Messages.HistoricalValue.getDefaultInstance()) return this;
        if (other.getT() != 0L) {
          setT(other.getT());
        }
        if (other.getV() != 0D) {
          setV(other.getV());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                t_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                v_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long t_ ;
      /**
       * <code>int64 t = 1;</code>
       * @return The t.
       */
      @java.lang.Override
      public long getT() {
        return t_;
      }
      /**
       * <code>int64 t = 1;</code>
       * @param value The t to set.
       * @return This builder for chaining.
       */
      public Builder setT(long value) {

        t_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 t = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        t_ = 0L;
        onChanged();
        return this;
      }

      private double v_ ;
      /**
       * <code>double v = 2;</code>
       * @return The v.
       */
      @java.lang.Override
      public double getV() {
        return v_;
      }
      /**
       * <code>double v = 2;</code>
       * @param value The v to set.
       * @return This builder for chaining.
       */
      public Builder setV(double value) {

        v_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double v = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        v_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.HistoricalValue)
    }

    // @@protoc_insertion_point(class_scope:proto.HistoricalValue)
    private static final proto.Messages.HistoricalValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Messages.HistoricalValue();
    }

    public static proto.Messages.HistoricalValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HistoricalValue>
        PARSER = new com.google.protobuf.AbstractParser<HistoricalValue>() {
      @java.lang.Override
      public HistoricalValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HistoricalValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HistoricalValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Messages.HistoricalValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UniversalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Universal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 type = 1;</code>
     * @return A list containing the type.
     */
    java.util.List<java.lang.Integer> getTypeList();
    /**
     * <code>repeated int32 type = 1;</code>
     * @return The count of type.
     */
    int getTypeCount();
    /**
     * <code>repeated int32 type = 1;</code>
     * @param index The index of the element to return.
     * @return The type at the given index.
     */
    int getType(int index);

    /**
     * <code>repeated bytes messages = 2;</code>
     * @return A list containing the messages.
     */
    java.util.List<com.google.protobuf.ByteString> getMessagesList();
    /**
     * <code>repeated bytes messages = 2;</code>
     * @return The count of messages.
     */
    int getMessagesCount();
    /**
     * <code>repeated bytes messages = 2;</code>
     * @param index The index of the element to return.
     * @return The messages at the given index.
     */
    com.google.protobuf.ByteString getMessages(int index);
  }
  /**
   * Protobuf type {@code proto.Universal}
   */
  public static final class Universal extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Universal)
      UniversalOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Universal.class.getName());
    }
    // Use Universal.newBuilder() to construct.
    private Universal(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Universal() {
      type_ = emptyIntList();
      messages_ = emptyList(com.google.protobuf.ByteString.class);
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Messages.internal_static_your_package_Universal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Messages.internal_static_your_package_Universal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Messages.Universal.class, proto.Messages.Universal.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList type_ =
        emptyIntList();
    /**
     * <code>repeated int32 type = 1;</code>
     * @return A list containing the type.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getTypeList() {
      return type_;
    }
    /**
     * <code>repeated int32 type = 1;</code>
     * @return The count of type.
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated int32 type = 1;</code>
     * @param index The index of the element to return.
     * @return The type at the given index.
     */
    public int getType(int index) {
      return type_.getInt(index);
    }
    private int typeMemoizedSerializedSize = -1;

    public static final int MESSAGES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> messages_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <code>repeated bytes messages = 2;</code>
     * @return A list containing the messages.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated bytes messages = 2;</code>
     * @return The count of messages.
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated bytes messages = 2;</code>
     * @param index The index of the element to return.
     * @return The messages at the given index.
     */
    public com.google.protobuf.ByteString getMessages(int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getTypeList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(typeMemoizedSerializedSize);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeInt32NoTag(type_.getInt(i));
      }
      for (int i = 0; i < messages_.size(); i++) {
        output.writeBytes(2, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(type_.getInt(i));
        }
        size += dataSize;
        if (!getTypeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        typeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < messages_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(messages_.get(i));
        }
        size += dataSize;
        size += 1 * getMessagesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Messages.Universal)) {
        return super.equals(obj);
      }
      proto.Messages.Universal other = (proto.Messages.Universal) obj;

      if (!getTypeList()
          .equals(other.getTypeList())) return false;
      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTypeList().hashCode();
      }
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Messages.Universal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.Universal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.Universal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.Universal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.Universal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Messages.Universal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Messages.Universal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.Messages.Universal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.Messages.Universal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.Messages.Universal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Messages.Universal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.Messages.Universal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Messages.Universal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Universal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Universal)
        proto.Messages.UniversalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Messages.internal_static_your_package_Universal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Messages.internal_static_your_package_Universal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Messages.Universal.class, proto.Messages.Universal.Builder.class);
      }

      // Construct using proto.Messages.Universal.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = emptyIntList();
        messages_ = emptyList(com.google.protobuf.ByteString.class);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Messages.internal_static_your_package_Universal_descriptor;
      }

      @java.lang.Override
      public proto.Messages.Universal getDefaultInstanceForType() {
        return proto.Messages.Universal.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Messages.Universal build() {
        proto.Messages.Universal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Messages.Universal buildPartial() {
        proto.Messages.Universal result = new proto.Messages.Universal(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.Messages.Universal result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          type_.makeImmutable();
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          messages_.makeImmutable();
          result.messages_ = messages_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Messages.Universal) {
          return mergeFrom((proto.Messages.Universal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Messages.Universal other) {
        if (other == proto.Messages.Universal.getDefaultInstance()) return this;
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            type_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            messages_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureTypeIsMutable();
                type_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureTypeIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  type_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 18: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureMessagesIsMutable();
                messages_.add(v);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList type_ = emptyIntList();
      private void ensureTypeIsMutable() {
        if (!type_.isModifiable()) {
          type_ = makeMutableCopy(type_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @return A list containing the type.
       */
      public java.util.List<java.lang.Integer>
          getTypeList() {
        type_.makeImmutable();
        return type_;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @return The count of type.
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @param index The index of the element to return.
       * @return The type at the given index.
       */
      public int getType(int index) {
        return type_.getInt(index);
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @param index The index to set the value at.
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          int index, int value) {

        ensureTypeIsMutable();
        type_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @param value The type to add.
       * @return This builder for chaining.
       */
      public Builder addType(int value) {

        ensureTypeIsMutable();
        type_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @param values The type to add.
       * @return This builder for chaining.
       */
      public Builder addAllType(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, type_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> messages_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureMessagesIsMutable() {
        if (!messages_.isModifiable()) {
          messages_ = makeMutableCopy(messages_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @return A list containing the messages.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getMessagesList() {
        messages_.makeImmutable();
        return messages_;
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @return The count of messages.
       */
      public int getMessagesCount() {
        return messages_.size();
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @param index The index of the element to return.
       * @return The messages at the given index.
       */
      public com.google.protobuf.ByteString getMessages(int index) {
        return messages_.get(index);
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @param index The index to set the value at.
       * @param value The messages to set.
       * @return This builder for chaining.
       */
      public Builder setMessages(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @param value The messages to add.
       * @return This builder for chaining.
       */
      public Builder addMessages(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMessagesIsMutable();
        messages_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @param values The messages to add.
       * @return This builder for chaining.
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes messages = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessages() {
        messages_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.Universal)
    }

    // @@protoc_insertion_point(class_scope:proto.Universal)
    private static final proto.Messages.Universal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Messages.Universal();
    }

    public static proto.Messages.Universal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Universal>
        PARSER = new com.google.protobuf.AbstractParser<Universal>() {
      @java.lang.Override
      public Universal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Universal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Universal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Messages.Universal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
   

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_your_package_Historical_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_your_package_Historical_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_your_package_HistoricalValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_your_package_HistoricalValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_your_package_Universal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_your_package_Universal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\014proto\"\\\n\nHistor" +
      "ical\022\017\n\007batchid\030\001 \001(\003\022\016\n\006sensor\030\002 \001(\t\022-\n" +
      "\006values\030\003 \003(\0132\035.proto.HistoricalV" +
      "alue\"\'\n\017HistoricalValue\022\t\n\001t\030\001 \001(\003\022\t\n\001v\030" +
      "\002 \001(\001\"+\n\tUniversal\022\014\n\004type\030\001 \003(\005\022\020\n\010mess" +
      "ages\030\002 \003(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_your_package_Historical_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_your_package_Historical_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_your_package_Historical_descriptor,
        new java.lang.String[] { "Batchid", "Sensor", "Values", });
    internal_static_your_package_HistoricalValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_your_package_HistoricalValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_your_package_HistoricalValue_descriptor,
        new java.lang.String[] { "T", "V", });
    internal_static_your_package_Universal_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_your_package_Universal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_your_package_Universal_descriptor,
        new java.lang.String[] { "Type", "Messages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
